internal/devices/devices.go
Das sollte das Problem mit den mehrfach vergebenen IPv6 Adressen lösen.
Anstatt die Gateway- & Netzwerkadressen an das existierende Array mit allen bereits benutzten Adressen anzuhängen wurde es überschreiben, was im Endeffekt dazu führte dass alle Clients die ::2 zugeteilt bekommen.
Fix getestet, sollte funktionieren.
=> Fix duplicate address detection

.github/workflows/build.yaml
This repo is currently missing any sort of CI / PR tests.
This means that problems with the changes can only be discovered through manual review (by another person) or after merging it and waiting for the deployment workflow to fail or finish.
It would be preferable to have some automated feedback right away, without having to wait for review or merge.
This reworks the currently defunct `build.yaml` workflow file to build the Docker image in pull requests, to give us some basic CI / validation and catch basic errors.
Unfortunately wg-access-server doesn't have any sort of unit testing set up, neither for the JS frontend code nor the Go backend code, so we can only check whether everything builds successfully.
The workflow is similar to the deployment workflow (docker.yml), except it only …
=> Add pull request build workflow

internal/storage/sql.go
This is a cherry-pick of https://github.com/Place1/wg-access-server/pull/135 fixing issue https://github.com/Place1/wg-access-server/issues/134
It has been slightly changed from @Nox-404's solution, using `url.Host` instead of `url.Hostname()` and `url.Port()` joined separately, as the second one would cause issues with raw IPv6 addresses (which `url.Hostname()` returns _without_ enclosing brackets). `url.Host` returns host and port already combined, with brackets for IPv6 addresses.
=> Fix mysql connection string

.dockerignore, .github/workflows/docker.yml
Our Docker image builds take around one hour to build and push to the registry:
We build for three different (emulated) architectures, without any caching, which takes a lot of time.
While pushes usually aren't urgent to publish to the world, there are occasions where you want to make use of newly pushed changes quickly.
Since we also directly push to `:latest`, there is always a race condition between parallel builds. With long running builds there is also an increased risk of overlapping builds, where the newer one finishes first and the older one then overwrites `:latest`.
It's also nice not to burn through CPU cycles if you don't need to.
Now we let buildx/BuildKit use the GitHub Action cache, see https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cac …
=> Use GitHub cache for building deployment Docker images

internal/dnsproxy/server.go
The proxy always queried *all* upstream servers and returned the last good response,
instead of returning the first good one.
This resulted both in unnecessary DNS traffic and load on upstream servers,
as well as increased response times.
Now the loop is properly short-circuited when a good response has been found.
=> Fix DNS proxy upstream lookup loop

.github/workflows/build.yml, .github/workflows/docker.yml
We now use the metadata action for tags & labels of our images (https://github.com/docker/metadata-action#usage, https://docs.github.com/en/actions/publishing-packages/publishing-docker-images)
Please have a look if I did everything right
Closes #68
=> Now using the metadata action for tags & labels

.github/workflows/build.yml
Fix-up of #70, probably a mis-cut/-paste, and I missed it in the final review
([Link to warnings](https://github.com/freifunkMUC/wg-access-server/actions/runs/1747870073))
=> Remove left-over label line

go.mod, go.sum
We now have [our own fork](https://github.com/freifunkMUC/pg-events) of place1's pg-events, which is running Dependabot and has a few updated dependencies.
This adds a `replace` directive just like for `wg-embed`.
Fixes #79
=> Switch to our own pg-events fork

Dockerfile
We've encountered the image publish workflow repeatedly failing with network problems, like
```
#110 [linux/arm/v7 website  7/11] RUN npm ci --no-audit --prefer-offline
#110 325.7 npm ERR! code ERR_SOCKET_TIMEOUT
#110 325.7 npm ERR! network Socket timeout
#110 325.7 npm ERR! network This is a problem related to network connectivity.
#110 325.7 npm ERR! network In most cases you are behind a proxy or have bad network settings.
#110 325.8 npm ERR! network 
#110 325.8 npm ERR! network If you are behind a proxy, please make sure that the
#110 325.8 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
#110 327.1 
#110 327.1 npm ERR! A complete log of this run can be found in:
#110 327.1 npm ERR!     /root/.npm/_logs/2022-01-26T15_26_51_037Z-debug-0.log
#110 ERROR: process …
```
=> Always run npm build stage on host-native platform

.github/buildkitd.toml, .github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/linting.yml
This builds and publishes the Docker image for ppc64le and s390x as requested by @GoliathLabs in #76.
To reduce the effect of the additional architectures on build time (which can cause ugly race conditions where an image of an earlier commit is pushed later as `latest` or `master` than the actually latest commit), the parallel jobs that buildx can run at the same time is now limited to `4` (instead of unlimited), which might or might not reduce context switches and memory consumption.
It did at least show an improvement in my testing of around 20% for completely uncached runs: 
(But I can't rule out that this wasn't just caused by the actions running at slightly different times on different runners with different load)
See also: …
=> Build and publish ppc64le and s390x images, limit parallel buildx jobs to 4

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/linting.yml
The linting workflow does not run on PRs that only change markdown files. While this is nice in theory because we don't lint markdown files and it would save GitHub some computing power by not starting unnecessary workflows, this conflicts with the "Require successful status checks before merging" setting – those checks never succeed because they never run.
And apparently GitHub isn't smart enough to detect that and exclude them from the required list.
Now, GitHub suggests an [ugly hack as a workaround](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks). We are supposed to create duplicate workflows with the same name, that run …
=> Always run linting workflow

README.md
This generates a 64 character password by default when used with the `docker run` command. This might be more secure than using `example` in the workflow, since some just copy and paste the command anyway and thus use an insecure admin password.
=> Added: Strong admin password generation to default README

README.md, docker-compose.yml, docs/deployment/1-docker.md, docs/deployment/2-docker-compose.md
As it turns out, `CAP_NET_ADMIN` and the bind-mount of `/lib/modules` aren't enough to load the ip_tables/ip6_tables kernel modules.
`docker run` with `-v /lib/modules:/lib/modules` and `--cap-add NET_ADMIN` but without `--cap-add SYS_MODULE` results in
```
FATA[0000]main.go:129 failed to read table filter: running [/sbin/ip6tables -t filter -S WG_ACCESS_SERVER_FORWARD 1 --wait]: exit status 3: modprobe: can't load module ip6_tables (kernel/net/ipv6/netfilter/ip6_tables.ko): Operation not permitted
```
`docker run` with `--cap-add NET_ADMIN --cap-add SYS_MODULE` and without `-v /lib/modules:/lib/modules` returns
```
FATA[0000]main.go:129 failed to read table filter: running [/sbin/ip6tables -t filter -S WG_ACCESS_SERVER_FORWARD 1 --wait]: exit status 3: modprobe: can't change directory to …
```
=> Add CAP_SYS_MODULE to Docker commands and docker-compose.yml

README.md, docker-compose.yml, docs/deployment/1-docker.md, docs/deployment/2-docker-compose.md
I made some changes to the documentation with regards to Docker to make things a bit more clear.
- Instruct the user to load the `ip_tables`/`ip6_tables` instead of defaulting to the `SYS_MODULE` capability. Added instructions about running with `SYS_MODULE` if needed.
- This seems like the more proper/safe way to run the container, so I think this should be the default recommendation.
- Change `docker-compose.yml` in accordance with above.
- Also removed the top-level named volume. The volume driver should be local by default, so I don't think this is needed.
- Added IPv4-only docker-compose example.
- Add warning to Docker section in README about `SYS_MODULE`.
- Moved the `Running on Kubernetes` section in the README after the `Docker-Compose` section.
=> Don't add CAP_SYS_MODULE by default and other Docker documentation fixes

internal/devices/devices.go, internal/devices/metadata.go
`device.LastHandshakeTime` can be nil in some cases (newly created device?), which `devices.syncMetrics()` didn't account for in #66.
```
wg-access-server  | panic: runtime error: invalid memory address or nil pointer dereference
wg-access-server  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93fc8c]
wg-access-server  | 
wg-access-server  | goroutine 300 [running]:
wg-access-server  | github.com/freifunkMUC/wg-access-server/internal/devices.syncMetrics(0xc0000a5540)
wg-access-server  |     /code/internal/devices/metadata.go:33 +0x24c
wg-access-server  | github.com/freifunkMUC/wg-access-server/internal/devices.metadataLoop(0x0)
wg-access-server  |     /code/internal/devices/metadata.go:12 +0x1e
wg-access-server  | created by …
```
=> Fix panic on nil LastHandshakeTime in metadata sync

cmd/serve/main.go, go.mod, go.sum, internal/devices/devices.go, internal/services/api_router.go, internal/services/server_service.go, internal/storage/pgwatcher.go
This updates wg-embed and pg-events to their latest tags to pull in https://github.com/freifunkMUC/wg-embed/pull/8 and https://github.com/freifunkMUC/pg-events/pull/5 and removes the `replace directives`, after which it should finally be possible to download install the binary using `go install` for those that need it. (Of course, the frontend files still need to be downloaded and built separately).
=> Update wg-embed to v0.6.0 and pg-events to v0.4.0

cmd/serve/main.go, docs/2-configuration.md, pkg/authnz/authconfig/authconfig.go, pkg/authnz/router.go
* Allow disabling of basic auth by not providing any basic config && having another auth setup
* When only a single auth is enabled, don't bother with the selection of auth types screen, just start the process
As you might have been able to tell with all the recent PRs, I'm using the OIDC flow ~(I think I might have been the original one to abstract the gitlab flow out to oidc~ nope I abstracted storage). I'm trying out https://goauthentik.io/ which is an open source okta. The flow for it is not ideal.
auth.domain.com => select VPN => goto wg-access-server -> select oidc -> goto authentik -> back to wg-access server
With this patch it becomes
auth.domain.com => select VPN
Assuming no other auths are enabled.
Also, I don't need nor want a static admin password. I can either redploy if I …
=> When only a single auth is enabled, dont show auth selector

docs/3-storage.md
pgbouncer breaks LISTEN/NOTIFY in "Transaction pooling" mode: https://www.pgbouncer.org/features.html
> **SQL feature map for pooling modes**
>
> Feature | Session pooling | Transaction pooling
> -- | -- | --
> LISTEN/NOTIFY | Yes | Never
Our pg-watcher / pg-events / [github.com/lib/pq](https://github.com/lib/pq) depend on those though, in order to report back newly created devices to the wireguard interface.
Added a note to 3-storage.md to let people know to use "Session pooling" instead.
In the future we could consider an automatic fallback to gormwatcher. It doesn't work with HA, but would allow single-instance deployments behind "Transaction pooling" pgbouncers. If there's a supported way to detect whether we run behind pgbouncer and which mode it is in.
Fixes #151
=> Document pgbouncer not working in 'Transaction pooling' mode

cmd/serve/main.go, docs/2-configuration.md
Our cmdline argument / environment variable parsing library requires elements of lists in env vars to be separated by new line chars.
This is both unintuitive and inconvenient, apparently `export SOMETHING="A\nB"` does not work (but `export SOMETHING=$'A\nB'` [might](https://unix.stackexchange.com/a/20039)).
It would be nice if we could allow commas as well, which is pretty common.
Now for the two options that take a list, `WG_DNS_UPSTREAM` and `WG_VPN_ALLOWED_IPS`, if the parsing library only returns one element, we try to split it at `,`.
This does not only apply to when they are specified through env vars, but also through cmdline flags or the config file.
Currently this is pretty simple because none of these options allow input that contains a comma, if we ever do get such an option …
=> Allow comma as list separator for environment variables

internal/services/api_router.go, internal/services/health.go, internal/services/middleware.go, pkg/authnz/authconfig/oidc.go
While looking at #119 I discovered that the existing `RecoveryMiddleware` doesn't actually work for panics in gRPC code / API calls. This is because the grpc library handles the requests in goroutines, and `recover()` can only work for panics in the same goroutine.
https://github.com/grpc/grpc-go/blob/431ea809a7676e1da8d09c33ae0d31fcba85f1ff/server.go#L920-L923
And while it does recover for non-gRPC calls, like the login flow, the logging doesn't actually work because `ctxlogrus` is a noop logger in this case.
This can make setting up OIDC annoying like in #154, because it's just failing and not telling you why.
The OIDC callback handler is broken if the `name` claim is missing, despite it being optional in the [spec](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse) …
=> Fix grpc recover and logging

README.md, cmd/serve/main.go, docs/deployment/1-docker.md, go.mod, go.sum
This bumps wg-embed to v0.7.0 to pull in https://github.com/freifunkMUC/wg-embed/pull/9
See the linked pull request for more details.
To repeat the important things:
- We try to use the kernel module, if something throws an error while creating the interface we log it and automatically fall back to the embedded userspace/Go implementation.
- netlink will try to load the kernel module automatically, it only requires `CAP_NET_ADMIN` (already required for interface management), no `CAP_SYS_MODULE` or mount of `/lib/modules` into a Docker container.
However 1-docker.md still says to load it on the host if possible, as this will be stabler and more future-proof.
You can check the running implementation either by checking for the `falling back to embedded Go implementation` log line, or running …
=> Use WG kernel module implementation if available

cmd/serve/main.go, docs/4-auth.md, internal/services/device_service.go, internal/services/server_service.go, pkg/authnz/authconfig/authconfig.go, pkg/authnz/authconfig/basic.go, pkg/authnz/authconfig/simple.go, pkg/authnz/authsession/identity.go, pkg/authnz/authtemplates/base.go.html, pkg/authnz/authtemplates/login.go.html, pkg/authnz/authtemplates/simpleauth.go.html, pkg/authnz/authtemplates/templates.go, pkg/authnz/router.go
Browsers cache credentials of HTTP Basic Auth. When you click logout, the session cookie of wg-access-server gets reset, however when you click on login again the browser automatically answers the challenge without re-prompting for username and password.
This makes the logout kind of ineffective, which can be a security problem when you or your users have systems where multiple people can access the browser.
According to SO it might be possible to make browsers invalidate their credential cache when you send an XHR request that returns a 401 response. I don't really like that workaround.
Instead, I've decided to add a new "simple auth" backend, which works like any other login feature out there.
It has a login form and sends credentials via POST instead of the Basic Auth standard …
=> Add simple authentication backend to work around broken Basic Auth logout

pkg/authnz/router.go
In `AuthMiddleware.Middleware()` the function tries to log errors using `ctxlogrus`. This logger is a no-op whenever we are handling a non-gRPC request (see #155).
#179 reported a 500 error being returned to clients, without any errors being logged. The missing error log might be caused by the above mentioned problem. The error itself might be a issue of the OIDC provider, but we'll see.
Now we use `traces.Logger` instead, which is never a no-op, but still gives us a nice trace id in the log etc.
This should be the last occasion of `ctxlogrus` being used outside of a gRPC context.
Fixes #179 (at least the missing log part, if something else is broken on our side we'll reopen it)
=> Fix missing log entries for ClaimsMiddleware errors

website/public/index.html
There is no manifest.json in the repository, nor is it generated during build or dynamically on requests.
#203 reported that it causes CORS issues, while I haven't confirmed whether these issues exist and whether they are fixed by removing it, a reference to a nonexistent file shouldn't be there anyway.
Fixes #203
=> Remove reference to nonexistent manifest.json

requirements-docs.txt
The documentation fails to build for GitHub pages, see #210 
Looks like Jinja2 hat breaking changes it version 3.1.0 (because who cares about semver, right?) which affected mkdocs.
Fortunately mkdocs has taken care of it in release 1.2.4: https://www.mkdocs.org/about/release-notes/#version-124-2022-03-26
Upgrade the docs requirements to their latest versions, most importantly mkdocs from 1.2.3 to 1.3.0.
I've also changed all version specifiers to `~=`, which also allows releases with same MAJOR.MINOR but higher BUILD number.
Fixes #210
=> Fix GH Pages docs build

docs/4-auth.md, pkg/authnz/authconfig/oidc.go, pkg/authnz/authconfig/oidc_test.go, pkg/authnz/authruntime/runtime.go, pkg/authnz/authutil/random.go, pkg/authnz/router.go
This allows reading OIDC claims from the ID Token instead of querying the UserInfo endpoint. Both methods are valid, however some OIDC auth providers like ADFS do not support the UserInfo endpoint:
> The AD FS UserInfo endpoint always returns the subject claim as specified in the OpenID standards. AD FS doesn't support additional claims requested via the UserInfo endpoint.
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq#i-m-trying-to-get-more-claims-on-the-userinfo-endpoint--but-it-s-only-returning-subject--how-can-i-get-more-claims-
Querying the UserInfo endpoint might however return more up to date data, so we still default to it.
A new `claimsFromIDToken` option has been added to the OIDC config. It defaults to false, setting it to true makes wgas …
=> Add option to read claims from OIDC ID Token

go.mod, go.sum
From the [README](https://github.com/mattn/go-sqlite3#readme) of the project:
> Latest stable version is v1.14 or later, not v2.
NOTE: The increase to v2 was an accident. There were no major changes or features.
The v2 "releases" didn't have any noteworthy changes so there's no problem with "downgrading".
There have been many real releases since then with v1 version numbers. One of them got rid of that annoying C bindings build warning, hurray.
```
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
|          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
|          ^~~~~~~
```
We'll see what dependabot does with this, if it …
=> Upgrade go-sqlite3 to v1.14.14

cmd/serve/main.go, docs/4-auth.md, pkg/authnz/authconfig/oidc.go
This PR should allow admin to require OIDC claim to be present for user to be able to access wg-access-server.
Closes #200
=> Require claim to be present to allow access to the user

docs/4-auth.md, pkg/authnz/authconfig/authconfig.go, pkg/authnz/router.go
When running multiple replicas in kubernetes users are getting "no session" error when trying to authenticate. It's caused by random session cookie secret generated differently for each POD.
=> feat: specify stable session cookie secret for HA setup

pkg/authnz/router.go
Fixup of #263 
Similar error to https://github.com/freifunkMUC/wg-access-server/pull/259#discussion_r1014868820, unfortunately I missed this one.
If `sessionStore` isn't specified at all in the config, `AuthConfig.SesstionStore` is `nil` (as it is a pointer), and needs to be checked for nil-ness first before accessing its member `Secret`.
=> Fix nil pointer dereference without SessionStore config

internal/devices/devices.go
You can overwrite an existing device configuration with a new one by reusing the same name.
Fixes #260
=> Add check if device name is already used

.github/dependabot.yml
All the recent Dependabot PRs had the following error message:
> Dependabot tried to add `@freifunkMUC/salt-stack` as a reviewer to this PR, but received the following error from GitHub:
> 
> ```
> POST https://api.github.com/repos/freifunkMUC/wg-access-server/pulls/332/requested_reviewers: 422 - Reviews may only be requested from collaborators. One or more of the teams you specified is not a collaborator of the freifunkMUC/wg-access-server repository. // See: https://docs.github.com/rest/reference/pulls#request-reviewers-for-a-pull-request
> ```
https://github.com/freifunkMUC/wg-access-server/pull/332#issuecomment-1450767151
I believe the review requests never worked, but now Dependabot explicitly shows that it encountered this error.
We have the freifunkMUC/wg-access team nowadasy, …
=> Dependabot: Request review from wg-access team

internal/devices/devices.go, internal/services/device_service.go, website/src/components/AddDevice.tsx, website/src/components/GetConnected.tsx
Hi,
This is a PR in a serie of 6 PRs, as it was asked to split https://github.com/freifunkMUC/wg-access-server/pull/294 up into multiple PRs.
**Serie:**
* **(THIS PR)** feature/bring-your-own-public-key
* feature/remove-all-devices-for-user
* feature/purge-inactive-devices
* feature/health-check
* hygiene/put-common-auth-logic-into-func
* feature/pre-shared-keys 
**Feature:**
This feature extends the wg-access-server, enabling the user to bring its own public key, instead of it being generated by the frontend. Reason for this is that the private key (generated in the browser), should in some circumstance not touch the web in any way.
This adds a new form input to "Add Device":
=> Bring your own public key

cmd/serve/main.go, go.mod, go.sum, internal/devices/devices.go, internal/services/health.go, internal/storage/contracts.go, internal/storage/inmemory.go, internal/storage/sql.go
Hi,
This is a PR in a serie of 6 PRs, as it was asked to split https://github.com/freifunkMUC/wg-access-server/pull/294 up into multiple PRs.
**Serie:**
* feature/bring-your-own-public-key
* feature/remove-all-devices-for-user
* feature/purge-inactive-devices
* **(THIS PR)** feature/health-check
* hygiene/put-common-auth-logic-into-func
* feature/pre-shared-keys 
**Dependency**
This PR depends on https://github.com/freifunkMUC/wg-embed/pull/15 and **its version has to be updated before this PR can be merged**.
**Feature:**
This feature extends the wg-access-server with proper health checks. It pings the embedded wireguard and the storage backend.
closes: https://github.com/freifunkMUC/wg-access-server/issues/100
=> health check

cmd/serve/main.go, internal/services/device_service.go, internal/services/server_service.go, pkg/authnz/authconfig/basic.go, pkg/authnz/authconfig/gitlab.go, pkg/authnz/authconfig/oidc.go, pkg/authnz/authconfig/simple.go, pkg/authnz/authsession/claims.go, pkg/authnz/router.go, proto/Dockerfile
Hi,
This is a PR in a serie of 6 PRs, as it was asked to split https://github.com/freifunkMUC/wg-access-server/pull/294 up into multiple PRs.
**Serie:**
* feature/bring-your-own-public-key
* feature/remove-all-devices-for-user
* feature/purge-inactive-devices
* feature/health-check
* **(THIS PR)** hygiene/put-common-auth-logic-into-func
* feature/pre-shared-keys 
**Code Hygiene:**
There are no new features but some cleanups:
* hardcoded checks are outsourced in a function
* login related code is moved to the authnz package
* a failed login gives reasonable status codes
* the node version for building the proto stubs is updated
=> put common auth logic into func

.dockerignore, .gitignore
This keeps the workspace clean for IntelliJ users.
=> Adds IntelliJ IDEA project files to `.gitignore` and `.dockerignore`.

docs/4-auth.md, pkg/authnz/authconfig/authconfig.go, pkg/authnz/authconfig/basic.go, pkg/authnz/authconfig/gitlab.go, pkg/authnz/authconfig/oidc.go, pkg/authnz/authconfig/simple.go, pkg/authnz/authruntime/runtime.go, pkg/authnz/authtemplates/login.go.html, pkg/authnz/router.go
This is supposed to improve the usability for non-IT corporate users:
We had a hard time* to convince our technically less inclined users that 'OIDC' in fact means our companys Keycloak SSO server. I always wished I could arbitrarily name the login buttons; hence this feature.
What do you think?
(* actually not _really_ hard, but for the sake of the argument... :grimacing: )
---
Given this config file extract:
```
...
auth:
...
oidc:
name: "MyCompany SSO"
...
gitlab:
name: "MyCompany Gitlab"
...
```
the login screen previously looked like this:
and with this change would look like this:
To implicitly reproduce the old behavior one would need to set the name to the type:
```
gitlab:
name: "gitlab"
```
=> Adds the auth methods 'name' field to the login buttons, if it differs from the auth type.

requirements-docs.txt
This PR updates the pymdown-extensions to a non-vulnerable version.
Arbitrary file read when using include file syntax.
By using the syntax --8<--"/etc/passwd" or --8<--"/proc/self/environ" the content of these files will be rendered in the generated documentation. Additionally, a path relative to a specified, allowed base path can also be used to render the content of a file outside the specified base paths: --8<-- "../../../../etc/passwd".
Within the Snippets extension, there exists a base_path option but the implementation is vulnerable to Directory Traversal.
The vulnerable section exists in get_snippet_path(self, path) lines 155 to 174 in snippets.py.
```
base = "docs"
path = "/etc/passwd"
filename = os.path.join(base,path) # Filename is now /etc/passwd
```
```
import markdown …
```
=> Update pymdown-extenstions to non-vuln version

website/src/components/Navigation.tsx, website/src/index.css
Proposal for the change of this very generic 'Welcome' banner in the navigation bar to the project name 'wg-access-server'.
Before:
After:
What do you think?
=> Change welcome title to project name

.typos.toml, cmd/serve/main.go, internal/config/config.go, internal/devices/devices.go, internal/devices/inactive.go, internal/devices/metadata.go, internal/dnsproxy/server.go, internal/network/network.go, internal/services/device_service.go, internal/services/website_router.go, internal/storage/contracts.go, internal/storage/contracts_test.go, main.go, pkg/authnz/authconfig/basic.go, pkg/authnz/authconfig/oidc.go, pkg/authnz/authsession/session.go, pkg/authnz/router.go
by:
- capitalizing log messages,
- adding additional logging, e.g. for user logins (session creation), and
- reducing the log level of these spammy grpc `info` lines to `debug`.
---
In our instance there are quite a lot of log lines like these:
```
INFO[0010]options.go:220 finished unary call with code OK              grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2023-07-02T20:38:50+02:00" grpc.time_ms=0.258 span.kind=server system=grpc trace.id=a34950b0-b843-4844-b726-2b0abc543a70
```
By reducing their level to `debug` they are now filtered in the `info` setting.
What do you think?
=> Improves logging

website/src/pages/admin/AllDevices.tsx
Adds an indicator for the number of devices (online vs total) and the number of users on the 'All Devices' page.
Before:
After:
What do you think?
=> Adds a device and user count the the all devices page.

cmd/serve/main.go, pkg/authnz/authconfig/oidc.go
=> Gracefully terminates if configured OIDC auth server is not present on application start.

internal/services/api_router.go, internal/traces/traces.go, main.go
So.. after I unsuccessfully tried to demote these GRPC `INFO` log statements to `DEBUG` level in #416 this is now my next try!
We are talking about these statements:
```
INFO[0011]options.go:220 finished unary call with code OK              grpc.code=OK grpc.method=ListAllDevices grpc.service=proto.Devices grpc.start_time="2023-09-09T14:28:41+02:00" grpc.time_ms=0.515 span.kind=server system=grpc trace.id=5b465b01-227c-4281-b2b2-966b4baa914c                    
INFO[0011]options.go:220 finished unary call with code OK              grpc.code=OK grpc.method=ListUsers grpc.service=proto.Users grpc.start_time="2023-09-09T14:28:41+02:00" grpc.time_ms=0.435 span.kind=server system=grpc trace.id=09ab9f84-aab1-4ed8-b5cf-2c960a996e2a
```
My position is that they should be actually of level `DEBUG` …
=> Hides GRPC request info logs

website/package-lock.json, website/package.json
On every JS library change this `name` item changed:
```
{
"name": "npm-proj-1694749545477-0.4344903296934472580hq7g",
"lockfileVersion": 2,
"requires": true,
"packages": {
...
```
and when building locally, it said:
```
"name": "website",
"lockfileVersion": 2,
"requires": true,
"packages": {
...
```
With the newly introduced property it should be constant.
=> Add package json name

cmd/serve/main.go
Fixing
```
Error: SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (staticcheck)
```
=> fix: golang linter (io package)

website/src/App.tsx, website/src/AppState.ts, website/src/components/Navigation.tsx, website/src/components/Present.tsx
added darkmode but atm only darkmode, no light mode:
i tried this form the Docs:
https://mui.com/material-ui/customization/dark-mode/#system-preference
but it did not work for me 
maybe add also a toggle like:
https://mui.com/material-ui/customization/dark-mode/#toggling-color-mode
"/"
"/admin/all-devices"  
"Popup"
=> Add darkmode after login

.github/workflows/linting.yml
We are experiencing issues with the go linter, let's have a look if we can improve the situation with an upgrade.
=> Updates `golangci-lint-action` to v4.

website/src/components/Devices.tsx, website/src/pages/admin/AllDevices.tsx
add error Info if Loading fails
I don't have any more working changes at the moment, so I'd be happy to make a release :)
=> Add more error handeling

.github/workflows/build.yml, .github/workflows/publish.yml
temporary downgrade image ci to `ubuntu-22.04`
failes some how for `linux/arm64/v8`
failes:
Succes:
=> temporary downgrade image ci

website/src/AppState.ts
Initialize dark mode state during app startup using system preferences and stored user settings to prevent momentary white flash on page load. Previously, dark mode was always initialized as false before checking preferences.
=> fix: prevent white flash by initializing dark mode from system preference

pkg/authnz/authtemplates/base.go.html
=> Make Go Login Form feeling a bit mordern 

.gitignore, Dockerfile, README.md, cmd/serve/main.go, docker-compose.yml, docs/2-configuration.md, docs/deployment/2-docker-compose.md, internal/config/config.go, internal/services/tls.go
- Updated Dockerfile to include OpenSSL for HTTPS support.
- Enhanced main.go to configure and start an HTTPS server with TLS certificate handling.
- Added new configuration options for HTTPS in config.go and updated documentation to reflect these changes.
- Implemented self-signed certificate generation in tls.go if no certificate is provided.
This enable HTTPS for the web UI, improving security for web traffic, also allows users to disable https example if the use a reverse Proxy.
https starts on default port 8443
`https://localhost:8443/`
http stats on default port 8000
`http://localhost:8000/`
Own TLS file:
```cmd
go run main.go serve --admin-password=test --https-cert-file local.crt --https-key-file local.key
```
No HTTPS:
```cmd
sudo go run main.go serve --admin-password=test …
```
=> feat: add HTTPS support for web UI

internal/network/network.go
When `WG_IPV4_NAT_ENABLED=false`, wg-access-server only creates iptables rules for outbound traffic (VPN clients → allowed networks) but not for return traffic (allowed networks → VPN clients). This causes connection timeouts as reply packets are dropped by the FORWARD chain.
The `configureForwardingv4` function only creates rules with pattern:
- `-s VPN_CIDR -d ALLOWED_CIDR -j ACCEPT` (outbound traffic)
But missing:
- `-s ALLOWED_CIDR -d VPN_CIDR -j ACCEPT` (return traffic)
When NAT is disabled, automatically create bidirectional rules for each allowed network in `WG_VPN_ALLOWED_IPS`. This ensures return traffic can flow back to VPN clients without requiring manual iptables configuration.
=> fix: Add return traffic rules when NAT is disabled

website/src/components/AddDevice.tsx
Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed
=> followup #847
