freifunkMUC/wg-access-server

.github/workflows/build.yaml, .github/workflows/docker.yml, Dockerfile
Good day,
I have updated the workflows as newer versions are available for some components. I also removed unsupported arguments of the build-push action in the Docker workflow, as they are not known to the action. Furthermore I've updated the Dockerfile to use newer versions of the respective components as well, but I was not able to update the Golang component to the latest version as it requires some changes in the code itself. As of today, I haven't written any Go code yet, so it may take a few hours to get things working with 1.16. But nonetheless, I've bumped up the Go version to the latest minor version of 1.13. Feel free to leave some feedback. Things seem to be working with the changes as I just installed the image on my server, but further testing may be required.
=> Updated: workflows & Dockerfile

README.md, docker-compose.yml
Good day,
I migrated the docker-compose.yml file so that it points to our image instead of Upstream's. Also, I have adapted the README.md file to us, mentioning for example the IPv6 implementation and announcing an updated documentation for the project soon.
=> Updated: README.md & docker-compose image location

.github/workflows/docker.yml
added additional architectures for the Docker image.
=> Added: arm64 & ppc64le

.github/workflows/build.yaml, .github/workflows/docker.yml, Dockerfile
I've added proper labeling to the Dockerfile
=> Added: Proper labeling

.github/workflows/tests.yaml, cmd/serve/main.go, internal/dnsproxy/server.go, internal/network/network.go, internal/services/api_router.go, internal/services/converters.go, internal/traces/traces.go, pkg/authnz/authconfig/basic.go, pkg/authnz/authconfig/oidc.go, pkg/authnz/router.go
Adding some lints and tests as well as a monthly dependabot scan for dependency updates
=> Added: tests & dependabot monthly scan

internal/network/network.go
In #13 we changed the iptables code to nmo ignore errors. Unfortunately, the code did rely on ignoring the errors – it tries to clear and recreate the chains regardless of whether they already exist:
(Thanks to @GoliathLabs for reporting and the screenshot)
If they already exist, creating will fail, if they don't already exist, clearing will fail.
Now the code is smarter: it checks whether a chain exists, and depending on that it either creates or clears (flushes) it.
As the code got a bit verbose, I factored it out into a new function, `clearOrCreateChain()`.
In my testing it now works fine regardless of whether the chains already exist or not.
=> Do not try to create existing iptables chains

Dockerfile
Updated: node 16 to bullseye & golang to 1.17.5
=> Updated: image tags

README.md, docs/deployment/1-docker.md
ip6tables needs to load modules thus docker needs access to them.
=> Fixes documentation bugs and adds IPv6 capability

TODO.md
Added some additional Features and things we've already added to the project (e.g. IPv6 support, ARM images etc)
=> Added: A few things we've done

CHANGELOG.md
I've added the changes we've made since we've forked from upstream. Those should be the key elements/changes)
=> Updated: Changelog to reflect the latest changes

README.md
This adds a new **Features** section listing the bigger, important features (did I forget anything?)
I've also rewritten the first part a bit, regarding being a fork and the state of the upstream project, and explicitly mentioning IPv6 support one more time.
Also fixed the Helm documentation link. Although I can't guarantee that the Helm charts are still up to date with the changes in our fork, I have no clue about k8s.
Fixes #60
=> Add features list to README, reorder introduction

deploy/helm/wg-access-server/values.yaml
=> Fixes Helm Chart to use the correct image

Dockerfile
=> Set node to a more fine-grained version

internal/services/website_router.go, internal/storage/sql.go, pkg/authnz/authsession/identity.go
```
cat .typos.toml
[files]
extend-exclude = ["go.sum", "package-lock.json"]
```
it can be hooked up as a github action - https://github.com/crate-ci/typos
=> used crate-ci/typos and found a few

pkg/authnz/authconfig/oidc.go
Turns out I had the wrong secret, but I wasn't able to diagnose it until I pulled it locally and printed out the err message.
=> Report why oidc failure is happening

deploy/helm/wg-access-server/README.md, deploy/helm/wg-access-server/templates/service.yaml, deploy/helm/wg-access-server/values.yaml
This resolves issue https://github.com/freifunkMUC/wg-access-server/issues/127
=> helm: add option to configure wireguard.service.nodePort

scripts/update-helm.py
The Helm update failed again for release v0.6.0:
https://github.com/freifunkMUC/wg-access-server/runs/5524171153?check_suite_focus=true
(#97)
But I didn't notice it for a while because the workflow itself was green. `subprocess.run` doesn't raise an exception if the subprocess returns with a non-zero exit code unless passed `check=True`.
Now we pass `check=True` and `capture_output=True` (second one not for a step where we redirect stdout), catch the error, format it nicely for GH Actions (more or less) and return a non-zero exit code outselves.
The Helm stuff is likely going to change soon, but until then at least we won't miss a failing workflow again.
=> Return error if Helm update script fails

pkg/authnz/authconfig/authconfig.go
make CI (Golang-CI (lint)) happy again
=> make linter happy again

.github/workflows/linting.yml, internal/devices/devices.go, internal/devices/inactive.go
fix linting errors introduced by 4766783 and 75ab900
=> fix linting errors introduced by 4766783 and 75ab900

internal/devices/devices.go, website/src/components/AddDevice.tsx, website/src/index.css
- Adds cause/message.
- Increases size and adds warning icon.
---
Before:
After:
=> Improves 'Add device' error message.

Dockerfile
Reverts freifunkMUC/wg-access-server#386
=> Revert "build(deps): bump alpine from 3.17.3 to 3.18.0"

website/package-lock.json, website/package.json, website/src/components/GetConnected.tsx, website/src/components/TabPanel.tsx
Replaces #333 which I had a hard time to rebase to the current state.
=> Bumps versions of `react` and `react-dom`. Fixes dependency issues and deprecated component invocations.

go.mod, go.sum
=> bump go-sqlite3 to v1.14.19

website/package-lock.json, website/package.json, website/src/Util.ts
fixes build errors with new date-fns update v3
=> fix: date-fns update

website/src/components/AddDevice.tsx, website/src/components/DeviceListItem.tsx, website/src/components/Devices.tsx, website/src/components/GetConnected.tsx, website/src/components/IconMenu.tsx, website/src/components/Info.tsx, website/src/components/Navigation.tsx, website/src/sdk/buildinfo_pb.ts, website/src/sdk/devices_pb.ts, website/src/sdk/server_pb.ts, website/src/sdk/users_pb.ts
Run prettier & protoc on project
=> feat: run prettier & protoc on project

pkg/authnz/authtemplates/base.go.html
Login Page:
Darkmode:
Lightmode:
=> add darkmode option for Login page

website/src/pages/admin/AllDevices.tsx
We could talk about the text, but I think some more information about what will be deleted would be good
User:
Device:
=> add more infos to delete Popup

website/src/pages/admin/AllDevices.tsx
Add Info that all devices from user gets deleted
=> Improve deleteUser confirmation message

website/src/App.tsx, website/src/components/Error.tsx
follo-wup #594
- Update the Error Box Element to the Styling of Loading 
- Remove Redundant Code in App.tsx
=> follow-up #594 (Error Box Styling, remove redudant code in App.tsx) 

website/src/components/DeviceListItem.tsx
- Add Confirm Button
- Remove Burger Menu
- Added Trashcan Icon
=> improve delete experience

website/src/components/Navigation.tsx
=> improve admin chip in darkmode

website/src/components/Navigation.tsx
Change the logout Text to an Icon
=> change to Logout to an Icon

website/index.html, website/public/manifest.json
"short_name": "WireGuard Access Portal",
"name": "WireGuard Access Portal",
"description": "WireGuard Access Portal is a web user interface for device management.",
short_name, name and description can still be changed
=> add manifest.json

website/src/components/DeviceListItem.tsx
=> fixes #611

website/src/components/Navigation.tsx
=> change all devices also to an icon

website/src/components/DeviceListItem.tsx, website/src/components/DeviceListItemSkeleton.tsx, website/src/components/Navigation.tsx, website/vite.config.ts
=> fixes #615 and #617

README.md
Add "Dark Mode Feature" Info in ReadMe and also some Screenshots of the "new" UI
=> Add "Dark Mode Feature" Info in ReadMe

.gitleaksignore
added a gitleak ignore file to ignore test wg keys
=> add gitleak ignore

mkdocs.yml
=> docs: add darkmode

.github/workflows/build.yml, .github/workflows/publish.yml
=> use buildtd instead of config

cmd/serve/main.go
fixes #792
https://pkg.go.dev/net#IP.IsUnspecified
=> add check if dst IP.IsUnspecified

docs/deployment/2-docker-compose.md
add treafik example as http is only allowed for localhost
=> add treafik example as http is only allowed for localhost

.golangci.yml, internal/devices/devices.go, internal/services/api_router.go, internal/services/health.go, internal/services/middleware.go, internal/services/website_router.go, internal/storage/contracts.go, internal/storage/contracts_test.go, internal/storage/pgwatcher.go, internal/storage/sql.go, pkg/authnz/authconfig/basic.go
=> Fix go linting

website/src/components/DeviceListItem.tsx
add title to delete Button (onHover)
=> add title to delete Button
